version: "3.9"

services:
  # Django App
  django_backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: citisafe_backend:latest
    ports:
      - "8093:8000" # Expose port 8083 for the web server
    environment:
      - PYTHONBUFFERED=1
    command:
      [
        "sh",
        "-c",
        "python project/manage.py collectstatic --noinput && python project/manage.py makemigrations && python project/manage.py migrate && python project/manage.py runserver 0.0.0.0:8000",
      ]
    volumes:
      - .:/code # For hotreloading
    depends_on:
      - redis # Add this to make sure Django can reach the Redis server

  # Redis Server
  redis:
    image: redis:latest
    ports:
      - "6380:6379" # Expose Redis default port

volumes:
  stude:
