# Generated by Django 5.0 on 2023-12-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
