# Generated by Django 4.2.4 on 2023-08-29 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_driver_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.classification'),
        ),
    ]
