# Generated by Django 4.2.4 on 2023-08-29 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_driver_classification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='user',
            new_name='officer',
        ),
    ]
