# Generated by Django 4.2.4 on 2023-10-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_rename_user_driver_officer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='contact_number',
        ),
    ]
