# Generated by Django 4.2.4 on 2023-10-02 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_remove_driver_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='email',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='eyes_color',
        ),
    ]
