# Generated by Django 4.2.4 on 2023-10-06 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_alter_driver_agency_code_alter_driver_classification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='agency_code',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='dl_codes',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='height',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='weight',
        ),
    ]
