# Generated by Django 4.2.4 on 2023-10-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_remove_driver_agency_code_remove_driver_blood_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
