# Generated by Django 4.2.4 on 2023-10-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0009_alter_driver_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
