# Generated by Django 4.2.6 on 2023-10-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0010_alter_driver_middle_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='classification',
            field=models.CharField(blank=True, choices=[('P', 'Professional'), ('NP', 'Non-Professional'), ('SP', 'Student-Permit'), ('O', 'Other')], max_length=2, null=True),
        ),
    ]
