# Generated by Django 4.2.4 on 2023-08-30 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_rename_initial_registered_owner_middle_initial'),
        ('traffic_ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_tickets', to='vehicles.vehicle'),
        ),
    ]
