# Generated by Django 4.2.4 on 2023-09-02 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='traffic_violation_ID',
        ),
    ]
