# Generated by Django 4.2.7 on 2023-11-30 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ticket.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(max_length=255)),
                ('penalty_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.penalty')),
            ],
        ),
        migrations.CreateModel(
            name='traffic_violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_id', models.ManyToManyField(to='ticket.violation')),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('ticket_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('DROPPED', 'Dropped')], default='Pending', max_length=10)),
                ('place_violation', models.CharField(max_length=255)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signature/')),
                ('MFRTA_TCT_NO', models.BigIntegerField(default=ticket.models.ticket.generate_mfrta_tct_no, primary_key=True, serialize=False)),
                ('driver_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_tickets', to='vehicles.vehicle')),
                ('violations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.traffic_violation')),
            ],
        ),
    ]
