# Generated by Django 4.2.4 on 2023-09-15 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0004_rename_user_driver_officer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='registered_owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('year_model', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=50, unique=True)),
                ('make', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50)),
                ('vehicle_class', models.CharField(max_length=255)),
                ('body_markings', models.CharField(max_length=100)),
                ('driverID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('owner_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.registered_owner')),
                ('vehicle_type_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle_type')),
            ],
        ),
    ]
