# Generated by Django 4.2.4 on 2023-08-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registered_owner',
            old_name='initial',
            new_name='middle_initial',
        ),
    ]
