# Generated by Django 4.2.4 on 2023-10-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_rename_first_name_registered_owner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=50),
        ),
    ]
