# Generated by Django 4.2.7 on 2023-11-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_remove_vehicle_owner_id_vehicle_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
