# Generated by Django 4.2.6 on 2023-10-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='image/image.png', null=True, upload_to='profile_pics/'),
        ),
    ]
